name: Test and deploy Typescript Library
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  commit:
    runs-on: ubuntu-latest
    container: "denoland/deno:alpine"
    steps:
      - uses: actions/checkout@v3
      - name: Deno test
        run: deno test